### ISSUE TITLE
Query and dashboard example 

### ISSUE THREAD

**Issue by klebermagno** [shirosaidev/stocksight#12]
Can you provide , maybe export your dashboard ?
I don't have experience with Kibana + Elasticsearch I made this run but I can't show any data.

**Comment by shirosaidev** [comment]
Load 'stocksight' index in Kibana and import export.json file for visuals/dashboard.

**Comment by niraj97** [comment]
There is some issue while importing the export.json file.
File could not be read
[illegal_argument_exception] Could not find a timestamp in the sample provided

**Comment by klebermagno** [comment]
> There is some issue while importing the export.json file.
> File could not be read
> [illegal_argument_exception] Could not find a timestamp in the sample provided

Which version of Kibana and elastic search are you using ?
this project work in  Elasticsearch 5 and Kibana 5.

**Comment by niraj97** [comment]
sorry but I was not importing the file correctly. That is why I got this error.
But I would lie to ask the owner to update the export.json file for the latest version of the program as it seems that some of the parameters have been changed since you last uploaded  that file.
Thanks for all you work though.
